climbunity_app/main/routes.py
import os
import time
import random
from os.path import exists
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask_login import login_user, logout_user, login_required, current_user
from datetime import date, datetime
from climbunity_app.utils import FormEnum
from climbunity_app.models import *
from climbunity_app.main.forms import *
from climbunity_app.auth.forms import *

from climbunity_app.extensions import app, db, bcrypt

main = Blueprint("main", __name__)

##########################################
#           Routes                       #
##########################################

# homepage route 
@main.route('/')
def homepage():
    all_venues = Venue.query.all()
    routes = Route.query.all()
    return render_template('home.html', routes=routes, all_venues=all_venues)

######################
#  venue routes
######################

# create
@main.route('/new_venue', methods=['GET', 'POST'])
@login_required
def new_venue():
    form = VenueForm()
    if form.is_submitted():
        new_venue = Venue(
            name=form.name.data,
            address=form.address.data,
            open_hours=form.open_hours.data,
            description=form.description.data,
        )
        db.session.add(new_venue)
        db.session.commit()
        flash('New venue was created successfully.')
        return redirect(url_for('main.venue_detail', venue_id=new_venue.id))
    return render_template('new_venue.html', form=form)

# read and update
@main.route('/venue/<venue_id>', methods=['GET', 'POST'])
def venue_detail(venue_id):
    venue = Venue.query.get(venue_id)
    routes = Route.query.filter_by(venue_id=venue_id).all()
    form = VenueForm(obj=venue)

    if form.validate_on_submit():
        venue.name = form.name.data
        venue.address = form.address.data
        venue.open_hours = form.open_hours.data
        venue.description = form.description.data
        db.session.commit()
        flash('Venue was edited successfully.')
        return redirect(url_for('main.venue_detail', venue_id=venue.id))

    venue = Venue.query.get(venue_id)
    return render_template('venue_detail.html', form=form, routes=routes, venue=venue)

@main.route('/delete_venue/<venue_id>', methods=['POST'])
@login_required
def delete_venue(venue_id):
    venue = Venue.query.get(venue_id)
    for appointment in venue.booked_appointments:
        db.session.delete(appointment)
        db.session.commit()
    routes = Route.query.filter_by(venue_id=venue.id).all()
    for route in routes:
        for ascent in route.ascents_on_route:
            db.session.delete(ascent)
            db.session.commit()
        db.session.delete(route)
        db.session.commit()
    db.session.delete(venue)
    db.session.commit()
    flash(f"{venue.name} deleted!")
    return redirect(url_for("main.homepage"))

######################
#  climbing route routes
######################

# create
@main.route('/new_route', methods=['GET', 'POST'])
@login_required
def new_route():
    form = RouteForm()
    if form.validate_on_submit():
        image_exists = os.path.exists(f'../static/img/{form.photo_url.data}')
        if image_exists:
            image_url = form.photo_url.data
        else:
            image_url = '/static/img/no_image.jpeg'
        new_route = Route(
            name=form.name.data,
            venue_id = form.venue_id.data.id,
            setter_id = form.setter_id.data.id,
            grade=form.grade.data,
            photo_url=image_url,
            route_set_date=form.route_set_date.data,
            route_takedown_date=form.route_takedown_date.data,
        )
        db.session.add(new_route)
        db.session.commit()
        for style in form.route_styles.data:
            new_route.possible_route_styles.append(style)
        for tag in form.route_tags.data:
            new_route.route_tags.append(tag)
        db.session.commit()
        flash('New route was created successfully.')
        return redirect(url_for('main.route_detail', route_id=new_route.id))
    return render_template('new_route.html', form=form)

# read and update
@main.route('/route/<route_id>', methods=['GET', 'POST'])
def route_detail(route_id):
    route = Route.query.get(route_id)
    route_venue = Venue.query.get(route.venue_id)
    setter = User.query.get(route.setter_id)
    ratings = 0
    rating = 0
    if route.ascents_on_route:
        for ascent in route.ascents_on_route:
            ratings += ascent.send_rating
        rating = ratings/len(route.ascents_on_route)
    form = RouteForm(obj=route)
    if form.validate_on_submit():
        image_exists = os.path.exists(f'/static/img/{form.photo_url.data}')
        if image_exists:
            image_url = form.photo_url.data
        else:
            image_url = '/static/img/no_image.jpeg'
        route.name = form.name.data
        route.venue_id = form.venue_id.data.id
        route.grade = form.grade.data
        route.photo_url = image_url
        route.route_set_date = form.route_set_date.data
        route.route_takedown_date = form.route_takedown_date.data
        route.possible_route_styles.extend(form.route_styles.data)
        route.route_tags.extend(form.route_tags.data)
        db.session.commit()
        flash('Route was edited successfully.')
        return redirect(url_for('main.route_detail', route_id=route.id, route_venue=route_venue, setter=setter, rating=rating))
    item = Route.query.get(route_id)
    return render_template('route_detail.html', form=form, route=route, route_venue=route_venue, setter=setter, rating=rating)

# delete
@main.route('/delete_route/<route_id>', methods=['POST'])
@login_required
def delete_route(route_id):
    route = Route.query.get(route_id)
    for ascent in route.ascents_on_route:
        db.session.delete(ascent)
        db.session.commit()
    db.session.delete(route)
    db.session.commit()
    flash(f"{route.name} deleted!")
    return redirect(url_for("main.venue_detail", venue_id=route.venue_id))

######################
#  project list routes
######################

# read on user profile pages
# create
@main.route('/add_to_project_list/<route_id>', methods=['POST'])
@login_required
def add_to_project_list(route_id):
    route = Route.query.get(route_id)
    current_user.user_projects.append(route)
    db.session.commit()
    flash(f"{route.name} added to project list")
    return redirect(url_for("main.route_detail", route_id = route.id, user_id=current_user.id))

# update / delete
@main.route('/remove_from_project_list/<route_id>', methods=['POST'])
@login_required
def remove_from_project_list(route_id):
    route = Route.query.get(route_id)
    current_user.user_projects.remove(route)
    db.session.commit()
    flash(f"{route.name} removed from project list")
    return redirect(url_for("main.user_detail", user_id=current_user.id))

######################
#  ascent routes
######################

# create
@main.route('/log_ascent/<route_id>', methods=['GET', 'POST'])
@login_required
def log_ascent(route_id):
    route = Route.query.get(route_id)
    venue = Venue.query.get(route.venue_id)
    form = AscentForm()
    if form.validate_on_submit():
        new_ascent = Ascent(
            user_id = current_user.id,
            route_id = route.id,
            send_date = form.ascent_date.data,
            send_type = form.ascent_type.data,
            send_rating = form.rating.data,
            send_comments = form.comments.data
        )
        route.ascents_on_route.append(new_ascent)
        db.session.add(new_ascent)
        db.session.commit()
        flash('New ascent was logged successfully.')
        return redirect(url_for('main.route_detail', route_id=route.id, venue=venue))
    return render_template('new_ascent.html', route_id=route.id, route=route, venue=venue, form=form)

# delete (no update)
@main.route('/delete_ascent/<ascent_id>', methods=['POST'])
@login_required
def delete_ascent(ascent_id):
    ascent = Ascent.query.get(ascent_id)
    route = Route.query.get(ascent.route_id)
    route.ascents_on_route.remove(ascent)
    db.session.delete(ascent)
    db.session.commit()
    flash(f"{route.name} removed from ascent list")
    return redirect(url_for("main.user_detail", user_id=current_user.id))

######################
#  profile routes
######################

# user creation route is in auth routes
# display all profiles
@main.route('/users', methods=['GET', 'POST'])
def all_users():
    users = User.query.all()
    return render_template('all_users.html', users=users)  
  
# read specific profile
@main.route('/profile/<user_id>', methods=['GET', 'POST'])
def user_detail(user_id):
    routes = Route.query.all()
    venues = Venue.query.all()
    user = User.query.get(user_id)
    ascents = Ascent.query.filter_by(user_id=user_id).all() # fine for small data but should be built out to display only 3-5 results + option to see all on different page
    if current_user == user:
        form = SignUpForm(obj=user)
        return render_template('user_detail.html', routes=routes, ascents=ascents, venues=venues, user=user, form=form)  
    else:
        user = User.query.get(user_id)
    return render_template('user_detail.html', routes=routes, ascents=ascents, venues=venues, user=user)

# update profile
    
@main.route('/edit_profile/<user_id>', methods=['GET', 'POST'])
def edit_user_detail(user_id):
    routes = Route.query.all()
    user = User.query.get(user_id)
    ascents = Ascent.query.filter_by(user_id=user_id).limit(5).all()
    form = EditProfileForm(obj=user)
    if current_user == user:
        if form.validate_on_submit():
            user.first_name = form.first_name.data
            user.last_name = form.last_name.data
            user.address = form.address.data
            user.has_gear = form.has_gear.data
            user.user_does_styles.clear()
            user.user_does_styles.extend(form.climber_styles.data)
            flash('User profile was edited successfully.')

climbunity_app/templates/all_users.html
{% extends 'base.html' %}
{% block content %}

<h1>Climbunity Users</h1>

{% for user in users %}
<div class="user">
    <a href="/profile/{{ user.id }}">{{ user.username }}</a> - 
    {% if user.user_does_styles %}
    <p><strong>Climbing styles:</strong></p>
        <ul>
        {% for style in user.user_does_styles %}
            <li>{{ style }}</li>
        {% endfor %}
        </ul>
    {% endif %}
</div>
{% endfor %}

{% endblock %}

climbunity_app/templates/appointment_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>New Appointment</h1>

<form method="POST" action="{{ url_for('main.new_appointment') }}">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Please enter information for this appointment:</legend>
        {{ form.appointment_date.label }}
        {{ form.appointment_date }}
        <ul>
        {% for error in form.date.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>
        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

climbunity_app/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Climbunity</title>
        <link rel="icon" href="../static/img/favicon.ico" />
        <link rel="stylesheet" href="/static/style.css">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap" rel="stylesheet">
    </head>
    <body>
        <img class="header-image" src="../static/img/logo-no-background.png" />
        <div id="content">
            {% include 'partials/nav_buttons_partial.html' %}
            {% block content %}{% endblock %}
        </div>
    </body>
</html>

climbunity_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Climbunity - Find a climbing partner!</h1>

<p><em>Get out and add to your tick list!</em></p>
{% if all_venues %}
    <h2>Today's top venues:</h2>
    {% for venue in all_venues %}
        <div class="venue">
            <a href="/venue/{{ venue.id }}">{{ venue.name }}</a> - Number of tracked routes: {{ routes | selectattr('venue_id', 'equalto', venue.id) | list | length }}
            <p><strong>Address:</strong> {{ venue.address }}</p>
            {% if current_user.is_authenticated %}
                {% if current_user.is_admin %}
                <form method="POST" action="/delete_venue/{{ venue.id }}">
                    <input type="submit" class="delete" value="Delete venue">
                </form>
                {% endif %}
            {% endif %}
        </div>
    {% endfor %}
{% else %}
    <p>There are no venues yet. You should {% if not current_user.is_authenticated %}sign up and {% endif %}add some!</p>
{% endif %}

{% endblock %}

climbunity_app/templates/login.html
{% extends 'base.html' %}
{% block content %}

<h1>Log In</h1>

<form action="/login" method="POST">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter your credentials</legend>

        {{ form.username.label }}
        {{ form.username }}
        <ul>
        {% for error in form.username.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.password.label }}
        {{ form.password }}
        <ul>
        {% for error in form.password.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

climbunity_app/templates/new_appointment.html
{% extends 'base.html' %}
{% block content %}

<h1>New Appointment</h1>

<form method="POST" action="{{ url_for('main.new_appointment') }}">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Please enter information for this appointment:</legend>
        {{ form.appointment_datetime.label }}
        {{ form.appointment_datetime }}
        <ul>
        {% for error in form.appointment_datetime.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>
        {{ form.venue_id.label }}
        {{ form.venue_id }}
        <ul>
        {% for error in form.venue_id.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>
        {{ form.additional_guests.label }}
        {{ form.additional_guests }}
        <ul>
        {% for error in form.additional_guests.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

climbunity_app/templates/new_ascent.html
{% extends 'base.html' %}
{% block content %}

<h1>Log an ascent of {{ route.name }}</h1>

<form method="POST" action="/log_ascent/{{ route.id }}">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Ascent details:</legend>
        <p>{{ route.name }} - {{ route.grade }} @ {{ venue.name }}</p>
        {{ form.ascent_date.label }}
        {{ form.ascent_date }}
        <ul>
        {% for error in form.ascent_date.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.ascent_type.label }}
        {{ form.ascent_type }}
        <ul>
        {% for error in form.ascent_type.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>
        
        {{ form.rating.label }}
        {{ form.rating }}
        <ul>
        {% for error in form.rating.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>
        
        {{ form.comments.label }}
        {{ form.comments }}
        <ul>
            {% for error in form.comments.errors %}
                <li class="error">{{ error }}</li>
            {% endfor %}
        </ul>

        {{ form.submit }} 
    </fieldset>
</form>

{% endblock %}

climbunity_app/templates/new_route.html
{% extends 'base.html' %}
{% block content %}

<h1>New Route</h1>

<form method="POST" action="{{ url_for('main.new_route') }}">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Please enter information for this route:</legend>
        {% include 'partials/route_form_partial.html' %}
    </fieldset>
</form>

{% endblock %}

climbunity_app/templates/new_venue.html
{% extends 'base.html' %}
{% block content %}

<h1>New Climbing Venue</h1>

<form method="POST" action="{{ url_for('main.new_venue') }}">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Please the information for this climbing venue:</legend>
        {{ form.name.label }}
        {{ form.name }}
        <ul>
        {% for error in form.name.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>
        {{ form.address.label }}
        {{ form.address(placeholder="123 Road St, Townsville, State, Nice Country, A1A1A1") }}
        <ul>
        {% for error in form.address.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>
        {{ form.open_hours.label }}
        {{ form.open_hours }}
        <ul>
        {% for error in form.open_hours.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>
        {{ form.description.label }}
        {{ form.description }}
        <ul>
        {% for error in form.description.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>
        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

climbunity_app/templates/projects_appointments.html
<h2>Current Projects</h2>

{% if user.user_projects %}
    {% for route in user.user_projects%}
        <div>{{ route.name }} - {{ route.grade }}
            {% if user == current_user %}
                <form style="display: inline;" method="POST" action="/remove_from_project_list/{{ route.id }}">
                    <input style="margin: 0; padding: 0;" type="submit" value="delete"/>
                </form>
            {% endif %}
        </div>
    {% endfor %}
{% else %}
<p>No projects are currently being tracked.</p>
{% endif %}

<h2>Recent Ascents</h2>
{% if ascents %}
    <div>
        {% for ascent in ascents %}
            <p>{{ ascent.send_date }} - <a href="/route/{{ ascent.route_id }}" > {{ ascent.routes_ascended[0].name }}</a></p>
            {% if ascent.send_rating %}
                <p>Rating: {{ ascent.send_rating }}/5</p> 
            {% endif %}
            {% if ascent.send_comments %}
                <p>Comments {{ ascent.send_comments }}</p>
            {% endif %}
            {% if user == current_user %}
            <form method="POST" action="/delete_ascent/{{ ascent.id }}">
                <input type="submit" value="Delete ascent">
            </form>
            {% endif %}
        {% endfor %}
    </div>
{% else %}
    {% if current_user.id == user.id %}
        You haven't logged any ascents yet!
    {% else %}
        {{ user.first_name }} {{ user.last_name }} has not logged any ascents yet!
    {% endif %}  
{% endif %}

climbunity_app/templates/route_detail.html
{% extends 'base.html' %}
{% block content %}

    <h1>Route - {{ route.name }}</h1>

    {% if route.photo_url %}
        <p><img src="{{ route.photo_url }}" width="250px" height="250px"></p>    
    {% endif %}
    <div class="route-container">
        <div class="route-info">
            <p><strong>Venue:</strong> <a href="/venue/{{ route_venue.id }}">{{ route_venue }}</a></p>

            <p><strong>Grade:</strong> {{ route.grade }}</p>

            <p><strong>Set Date:</strong> {{ route.route_set_date }}</p>

            <p><strong>Takedown Date:</strong> {{ route.route_takedown_date }}</p>

            <p><strong>Route set by user:</strong> {{ setter }}</p>

            <p><strong>Route styles:</strong></p> 
            <ul>
                {% for style in route.possible_route_styles %}
                    <li>{{ style }}</li>
                {% endfor %}
            </ul>

            <p><strong>Route technical tags:</strong></p>
            <ul>
                {% for tag in route.route_tags %}
                    <li>{{ tag }}</li>
                {% endfor %}
            </ul>
        </div>
        <div class="route-social">
            {% if route.ascents_on_route %}
                <p><strong>Recent comments about this route:</strong></p>
                <ul>
                    {% for ascent in route.ascents_on_route %}
                        {% if ascent.send_comments %}
                            <li>{{ ascent.send_comments }}</li>
                        {% endif %}
                    {% endfor %}
                </ul>
                <p>Average rating: {{ rating }}</p>
            {% else %}
                <p>No comments yet... Log an ascent and leave some comments!</p>
            {% endif %}
        </div>
    </div>
    {% if current_user.is_authenticated %}
        {% include 'partials/project_ascent_buttons_partial.html' %}
        {% include 'partials/edit_route_partial.html' %}
    {% endif %}

{% endblock %}

climbunity_app/templates/signup.html
{% extends 'base.html' %}
{% block content %}

<h1>Sign Up</h1>

<form action="/signup" method="POST">
    {{ form.csrf_token }}
    <fieldset>
        {{ form.username.label }}
        {{ form.username }}
        <ul>
        {% for error in form.username.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.password.label }}
        {{ form.password }}
        <ul>
        {% for error in form.password.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.email.label }}
        {{ form.email }}
        <ul>
        {% for error in form.email.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.first_name.label }}
        {{ form.first_name }}
        <ul>
        {% for error in form.first_name.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.last_name.label }}
        {{ form.last_name }}
        <ul>
        {% for error in form.last_name.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.address.label }}
        {{ form.address }}
        <ul>
        {% for error in form.address.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.climber_styles.label }}
        {{ form.climber_styles }}
        <ul>
        {% for error in form.climber_styles.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.has_gear.label }}
        {{ form.has_gear }}
        <ul>
        {% for error in form.has_gear.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>
        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

climbunity_app/templates/user_detail.html
{% extends 'base.html' %}
{% block content %}

<h1> {{ user.username }}'s Profile</h1>
<p><strong>Name: </strong> {{ user.first_name }} {{ user.last_name }}</p>
<p><strong>Address: </strong> {{ user.address }}</p>
<h2>Climbing Styles</h2>

{% if user.user_does_styles %}
    <ul>
        {% for style in user.user_does_styles %}
            <li>{{ style }}</li>    
        {% endfor %}
    </ul>
{% endif %}

{% if user.has_gear %}
    <p>{{ user.username }} has their own climbing gear.</p>
{% else %}
    <p>{{ user.username }} does not have their own climbing gear.</p>
{% endif %}

{% include 'partials/projects_ascents_partial.html' %}

{% include 'partials/appointments_partial.html' %}

{% if user == current_user %}
    {% include 'partials/edit_profile_partial.html' %}
{% endif %}

{% endblock %}

climbunity_app/templates/venue_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Venue - {{ venue.name }}</h1>

<p><strong>Address / Location:</strong> {{ venue.address }}</p>

<p><strong>Hours of Operation:</strong> {{ venue.open_hours }}</p>

<p><strong>Description:</strong> {{ venue.description }}</p>

<h2>Routes</h2>

{% if routes %}
    <div class="routes">
        {% for route in routes %}
        <div class="route-details">
            <a href="/route/{{ route.id }}">
            <p><strong>{{ route.name }}</strong></p></a>
            <p><strong>Grade: {{ route.grade }}</strong></p>
            {% if current_user.is_authenticated %}
                {% include 'partials/project_ascent_buttons_partial.html' %}
            {% endif %}
        </div>
        {% endfor %}
    </div>
{% else %}
    There are no routes listed for this venue.  You should {% if not current_user.is_authenticated %}sign up and {% endif %}add some!
{% endif %}

{% if current_user.username %}
    {% include 'partials/edit_venue_partial.html' %}
{% endif %}

{% endblock %}